### ISSUE TITLE
single configuration for all jobs

### ISSUE THREAD

**Issue by itnazeer** [rundeck-plugins/slack-incoming-webhook-plugin#7]
So, I have to update every job to which channel it need to send notification, need to webhook url, token id in every job.
Can we do this global instead of adding webhook url, token id etc in every job?
please suggest on this.

**Comment by ltamaster** [comment]
Hi @itnazeer,

You can set the attributes at project or framework level

<img width="1085" alt="Screenshot 2019-04-24 12 24 00" src="https://user-images.githubusercontent.com/6034968/56676252-e29df200-668b-11e9-8ab3-1d9fb95a1fe7.png">

For example:
```
project.plugin.Notification.SlackNotification.webhook_base_url=https://hooks.slack.com/services
project.plugin.Notification.SlackNotification.webhook_token= T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX
```

**Comment by itnazeer** [comment]
I have added in framework properties and restarted the the rundeck service, though I can't see slack notification enabled on jobs.

**Comment by ltamaster** [comment]
Any error on service.log?

**Comment by bradym** [comment]
@itnazeer You have to enable notification on individual jobs. 

If you leave the fields for WebHook Base URL, WebHook Token and Slack Channel blank it will use the values from framework.properties.

If you provide values for any of those fields, it will take precedence over what is specified in framework.properties. This can come in handy for testing or for jobs that should notify a channel other than the default.

**Comment by fdevans** [comment]
Closing as workaround/solution provided.  Let us know or re-open if you have having the same issue.
